### ISSUE TITLE
Film Negative tool deprecated.

### ISSUE THREAD

**Issue by atriantas** [artpixls/ART#343]
Why is the Film Negative going to be deprecated?
I think it is a good solution for film photographers.

**Comment by agriggio** [comment]
Hi, where did you get that? No tool is going to be deprecated, but some sliders might. That usually just means that there's a better way to achieve the same, but there's currently no plan to remove the settings in the future.

**Comment by atriantas** [comment]
Hi, I saw the icon with the exclamation mark.
Is this only for the Color Space?

![Film Negative deprecated](https://github.com/user-attachments/assets/a1d4210a-0c8f-4df6-9691-aefb23691dab)

**Comment by agriggio** [comment]
Yes
