### ISSUE TITLE
File browser: filtering on star ranking and color labels broken? [ART 1.24.2 - 1.24.4]

### ISSUE THREAD

**Issue by rjmoerland** [artpixls/ART#345]
I've just installed ART 1.24.3 and was about to resume a project I started in ART 1.24.1 where I had ranked some photos by giving them a star. To quickly find these photos back I pressed the "Show images ranked as 1-star" filter in the file browser, but I got a blank screen (no files shown). I installed ART 1.24.1 again and tried the filter there, and then I indeed got the files that I had ranked earlier. 

**Steps to reproduce (with 1.24.3):**
1. Open a folder with photos
2. Rank a photo with a star
3. Select "Show images ranked as 1-star"

**Expected result:**
The photo with the 1-star ranking is shown

**Actual result:**
No photos are shown

**Last-known working version:**
1.24.1

**First broken version:**
1.24.2

Fiddling a bit more, I found that when filtering on color label in 1.24.1, I got the result as expected (only files shown with selected color label). In 1.24.3, all files were shown regardless the state of the color label filter.

**Version info:**
Version: 1.24.3
Branch: 1.24.3
Commit: 0587264
Commit date: 2024-12-18
Compiler: cc 14.2.0
Processor: undefined
System: Windows
Bit depth: 64
Gtkmm: 3.24.9
Lensfun: 0.3.4.0
Exiv2: 0.27.7
LCMS2: 2.16-fastfloat
LibRaw: 0.22.0-Devel202403
OpenColorIO: 2.4.1
CTL interpreter: version 1
Build type: Release
Build flags:  -std=c++11 -ffp-contract=off  -Werror=unused-label -fno-math-errno -Wl,--stack,4194304 -Wall -Wuninitialized -Wno-deprecated-declarations -Wno-unused-result -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG -ftree-vectorize
Link flags:   
OpenMP support: ON
Mi-malloc: V2.1
Build OS: Windows
Build date: 2024-12-19T17:08:36Z

Thanks for looking into this!

**Comment by agriggio** [comment]
Hi,
confirmed, thanks for reporting! I'll try to see what is going on...

**Comment by rjmoerland** [comment]
Thanks for the quick fix! After trying multiple combinations of open source applications for culling and raw development, I found ART to be the best replacement for my former Bridge + Camera RAW workflow. I'm happy the file browser is back in all its glory :)
