### ISSUE TITLE
Feature request: metadata filter/search field - distinguish between JPG and jpg

### ISSUE THREAD

**Issue by paulmatthijsse** [artpixls/ART#346]
Hello, feature request: in the Navigator, distinguish in the metadata filter and the search field between JPG and jpg. The JPGs come from my camera, the jpgs are my saved edits. Would be nice to show just my edits, so jpgs. Thanks for reading.

**Comment by agriggio** [comment]
This would be quite unreliable, because there are popular file systems which are case insensitive

**Comment by paulmatthijsse** [comment]
Oops, didn't think about that, but you're right of course!
